/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Standard Webhook Headers
 */
export interface Headers {
  "webhook-id": string;
  "webhook-timestamp": string;
  "webhook-signature": string;
  [k: string]: unknown;
}
